import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Carbon Credit Calculator",
  description: "Generated by YIB",
  icons:"./forest.ico"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="shortcut icon" href='./forest.png'/>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
